### ISSUE TITLE
Sending streams

### ISSUE THREAD

**Issue by joakim5937x** [xuset/peer-relay#1]
Using this library for a project and it works great!

My only problem is that I need to send streams via webrtc once a direct p2p connection has been established. I have tried to implement this without any good success. Do you have any pointers or tips on where to start? 

Thanks!

**Comment by xuset** [comment]
Thanks, I'm glad it's working great for you! peer-relay is not really suitable for reliable in-order messages that streaming would need since all messages are relayed through a network of peers. What seems best to me is to send the webrtc signaling info through peer-relay so a direct p2p connection can be formed between the two peers. Hope this helps!

**Comment by joakim5937x** [comment]
Thanks! Yes this was the solution that I ended with after some hours of thinking!
